import { QuizQuestion } from '../../../../../types';

export const easyQuestions: QuizQuestion[] = [
  {
    id: 'cl8_ch6_t1_qe1',
    type: 'mcq',
    question: 'The cube of 5 is:',
    options: ['15', '25', '75', '125'],
    correctAnswer: '125',
    explanation: '5³ = 5 × 5 × 5 = 125 🧮',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t1_qe2',
    type: 'mcq',
    question: 'Which of the following is a perfect cube?',
    options: ['16', '27', '32', '50'],
    correctAnswer: '27',
    explanation: '27 = 3³ = 3 × 3 × 3, making it a perfect cube 📊',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t1_qe3',
    type: 'mcq',
    question: 'The cube root of 64 is:',
    options: ['2', '4', '6', '8'],
    correctAnswer: '4',
    explanation: '4³ = 4 × 4 × 4 = 64, so ∛64 = 4 🔢',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t1_qe4',
    type: 'mcq',
    question: 'Which number is NOT a perfect cube?',
    options: ['1', '8', '27', '36'],
    correctAnswer: '36',
    explanation: '36 is not a perfect cube as it cannot be expressed as n³ for any integer n 🚫',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t1_qe5',
    type: 'mcq',
    question: 'The cube of 0 is:',
    options: ['0', '1', '-1', 'None of these'],
    correctAnswer: '0',
    explanation: '0³ = 0 × 0 × 0 = 0 📝',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t1_qe6',
    type: 'mcq',
    question: 'The cube root of 8 is:',
    options: ['2', '3', '4', '6'],
    correctAnswer: '2',
    explanation: '2³ = 2 × 2 × 2 = 8, so ∛8 = 2 🎯',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t1_qe7',
    type: 'mcq',
    question: 'What is the cube of 6?',
    options: ['36', '120', '216', '360'],
    correctAnswer: '216',
    explanation: '6³ = 6 × 6 × 6 = 36 × 6 = 216 📊',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t1_qe8',
    type: 'mcq',
    question: 'The cube root of 1 is:',
    options: ['0', '1', '3', '1/3'],
    correctAnswer: '1',
    explanation: '1³ = 1 × 1 × 1 = 1, so ∛1 = 1 🔍',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t1_qe9',
    type: 'mcq',
    question: 'Which of the following is the cube of 4?',
    options: ['16', '32', '64', '128'],
    correctAnswer: '64',
    explanation: '4³ = 4 × 4 × 4 = 16 × 4 = 64 🧮',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t1_qe10',
    type: 'mcq',
    question: 'The cube of -2 is:',
    options: ['-8', '-6', '6', '8'],
    correctAnswer: '-8',
    explanation: '(-2)³ = (-2) × (-2) × (-2) = -8 🔢',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t1_qe11',
    type: 'mcq',
    question: 'The cube root of 125 is:',
    options: ['3', '5', '15', '25'],
    correctAnswer: '5',
    explanation: '5³ = 125, so ∛125 = 5 📏',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t1_qe12',
    type: 'mcq',
    question: 'What is the value of 2³?',
    options: ['4', '6', '8', '16'],
    correctAnswer: '8',
    explanation: '2³ = 2 × 2 × 2 = 8 🎯',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t1_qe13',
    type: 'mcq',
    question: 'The cube root of -27 is:',
    options: ['-3', '3', '-9', '9'],
    correctAnswer: '-3',
    explanation: '(-3)³ = -27, so ∛(-27) = -3 📊',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t1_qe14',
    type: 'mcq',
    question: 'What is the cube of 1/3?',
    options: ['1/3', '1/9', '1/27', '3'],
    correctAnswer: '1/27',
    explanation: '(1/3)³ = 1/3 × 1/3 × 1/3 = 1/27 🔢',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t1_qe15',
    type: 'mcq',
    question: 'How many natural numbers less than 100 are perfect cubes?',
    options: ['3', '4', '5', '6'],
    correctAnswer: '4',
    explanation: 'They are 1, 8, 27, and 64 (1³, 2³, 3³, and 4³) 📈',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t1_qe16',
    type: 'mcq',
    question: 'The value of ∛27 + ∛8 is:',
    options: ['3', '5', '6', '9'],
    correctAnswer: '5',
    explanation: '∛27 + ∛8 = 3 + 2 = 5 🧮',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 40,
  },
  {
    id: 'cl8_ch6_t1_qe17',
    type: 'mcq',
    question: 'If the volume of a cube is 8 cubic cm, what is the length of its edge?',
    options: ['2 cm', '3 cm', '4 cm', '8 cm'],
    correctAnswer: '2 cm',
    explanation: 'Volume = edge³, so edge = ∛8 = 2 cm 📏',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t1_qe18',
    type: 'mcq',
    question: 'Which number is a perfect cube?',
    options: ['12', '16', '18', '27'],
    correctAnswer: '27',
    explanation: '27 = 3³, making it a perfect cube 🎯',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t1_qe19',
    type: 'mcq',
    question: 'The cube root of 0.001 is:',
    options: ['0.1', '0.01', '0.001', '0.0001'],
    correctAnswer: '0.1',
    explanation: '0.1³ = 0.001, so ∛0.001 = 0.1 📊',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t1_qe20',
    type: 'mcq',
    question: 'Which is the smallest perfect cube among the following?',
    options: ['8', '27', '64', '125'],
    correctAnswer: '8',
    explanation: '8 = 2³, smaller than 27 = 3³, 64 = 4³, and 125 = 5³ 🔍',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  }
];
