import { QuizQuestion } from '../../../../../types';

export const mediumQuestions: QuizQuestion[] = [
  {
    id: 'cl8_ch7_t1_qm1',
    type: 'mcq',
    question: 'In a mixture of milk and water, the ratio of milk to water is 3:2. If 5 liters of water is added, the ratio becomes 3:4. How many liters of milk are there?',
    options: ['9', '10', '12', '15'],
    correctAnswer: '15',
    explanation: 'Let milk = 3x, water = 2x. After adding 5L: 3x/(2x+5) = 3/4, solving gives x = 5, so milk = 15L 📏',
    difficulty: 'medium',
    marks: 2,
    recommendedTime: 50,
  },
  {
    id: 'cl8_ch7_t1_qm2',
    type: 'mcq',
    question: 'A shopkeeper sold an item at 20% profit. If the selling price was ₹600, what was the cost price?',
    options: ['₹480', '₹500', '₹520', '₹550'],
    correctAnswer: '₹500',
    explanation: 'Let cost price = x. Then x + 20% of x = 600, so 1.2x = 600, thus x = 500 🧮',
    difficulty: 'medium',
    marks: 2,
    recommendedTime: 45,
  },
  {
    id: 'cl8_ch7_t1_qm3',
    type: 'mcq',
    question: 'The price of a phone was reduced by 12%. If the new price is ₹7,920, what was the original price?',
    options: ['₹8,800', '₹9,000', '₹9,200', '₹9,500'],
    correctAnswer: '₹9,000',
    explanation: 'Let original price = x. Then x - 12% of x = 7,920, so 0.88x = 7,920, thus x = 9,000 📊',
    difficulty: 'medium',
    marks: 2,
    recommendedTime: 45,
  },
  {
    id: 'cl8_ch7_t1_qm4',
    type: 'mcq',
    question: 'If a:b = 5:7 and b:c = 3:2, then a:c equals:',
    options: ['15:14', '5:7', '5:2', '15:4'],
    correctAnswer: '15:14',
    explanation: 'a:b = 5:7, so a:b:c = 5:7:c. Also, b:c = 3:2, so b:c = 7:7×(2/3). Thus a:c = 5:14/3, which is 15:14 🔢',
    difficulty: 'medium',
    marks: 2,
    recommendedTime: 50,
  },
  {
    id: 'cl8_ch7_t1_qm5',
    type: 'mcq',
    question: 'A sum of money is divided among A, B, and C in the ratio 2:3:5. If C gets ₹300 more than A, how much money does B get?',
    options: ['₹300', '₹450', '₹600', '₹750'],
    correctAnswer: '₹450',
    explanation: 'Let unit amount = x. Then C-A = 5x-2x = 3x = 300, so x = 100. Therefore B = 3x = 300 + 150 = 450 📝',
    difficulty: 'medium',
    marks: 2,
    recommendedTime: 50,
  },
  {
    id: 'cl8_ch7_t1_qm6',
    type: 'mcq',
    question: 'Three numbers are in the ratio 1:2:3, and their sum is 72. What is the middle number?',
    options: ['16', '24', '28', '36'],
    correctAnswer: '24',
    explanation: 'If ratio is 1:2:3, total parts = 6. Middle number = 2/6 × 72 = 24 🎯',
    difficulty: 'medium',
    marks: 2,
    recommendedTime: 45,
  },
  {
    id: 'cl8_ch7_t1_qm7',
    type: 'mcq',
    question: 'A student scored 68% marks in an exam. If he scored 408 marks, what was the maximum marks of the exam?',
    options: ['500', '550', '600', '650'],
    correctAnswer: '600',
    explanation: '68% of maximum marks = 408, so maximum marks = 408/0.68 = 600 🔍',
    difficulty: 'medium',
    marks: 2,
    recommendedTime: 45,
  },
  {
    id: 'cl8_ch7_t1_qm8',
    type: 'mcq',
    question: 'The ratio of present ages of Ram and Shyam is 3:4. If Ram will be 36 years old after 12 years, how old is Shyam now?',
    options: ['24 years', '28 years', '32 years', '36 years'],
    correctAnswer: '32 years',
    explanation: "Ram's current age = 36-12 = 24. If Ram:Shyam = 3:4, then Shyam's age = (4/3)×24 = 32 years 🧮",
    difficulty: 'medium',
    marks: 2,
    recommendedTime: 50,
  },
  {
    id: 'cl8_ch7_t1_qm9',
    type: 'mcq',
    question: 'In what ratio should a shopkeeper mix tea worth ₹240 per kg with tea worth ₹300 per kg to get a mixture worth ₹280 per kg?',
    options: ['1:2', '2:3', '1:3', '1:4'],
    correctAnswer: '1:2',
    explanation: 'Using the rule of alligation: (300-280)/(280-240) = 20/40 = 1:2 📊',
    difficulty: 'medium',
    marks: 2,
    recommendedTime: 50,
  },
  {
    id: 'cl8_ch7_t1_qm10',
    type: 'mcq',
    question: 'A school has 40% boys. If the number of girls is 540, what is the total number of students?',
    options: ['800', '900', '1000', '1200'],
    correctAnswer: '900',
    explanation: 'Let total students = x. Girls = 60% of x = 540, so x = 540/0.6 = 900 🎯',
    difficulty: 'medium',
    marks: 2,
    recommendedTime: 45,
  },
  {
    id: 'cl8_ch7_t1_qm11',
    type: 'mcq',
    question: 'The salaries of A and B are in the ratio 2:3. If A\'s salary increases by 50% and B\'s salary increases by 20%, what will be the new ratio of their salaries?',
    options: ['10:11', '10:12', '20:21', '3:4'],
    correctAnswer: '10:12',
    explanation: 'New ratio = 2×1.5:3×1.2 = 3:3.6 = 30:36 = 10:12 = 5:6 🔢',
    difficulty: 'medium',
    marks: 2,
    recommendedTime: 55,
  },
  {
    id: 'cl8_ch7_t1_qm12',
    type: 'mcq',
    question: 'A shopkeeper marks his goods at 40% above cost price and gives a discount of 20%. What is his profit percentage?',
    options: ['8%', '12%', '16%', '20%'],
    correctAnswer: '12%',
    explanation: 'Selling price = 140% × 80% of cost price = 112% of cost price, so profit = 12% 📏',
    difficulty: 'medium',
    marks: 2,
    recommendedTime: 50,
  },
  {
    id: 'cl8_ch7_t1_qm13',
    type: 'mcq',
    question: 'If 30% of A = 40% of B, then A:B equals:',
    options: ['3:4', '4:3', '3:7', '7:3'],
    correctAnswer: '4:3',
    explanation: 'If 0.3A = 0.4B, then A/B = 0.4/0.3 = 4/3, so A:B = 4:3 🧮',
    difficulty: 'medium',
    marks: 2,
    recommendedTime: 45,
  },
  {
    id: 'cl8_ch7_t1_qm14',
    type: 'mcq',
    question: 'A mixture contains milk and water in the ratio 5:3. If 4 liters of water is added to this mixture, the ratio becomes 5:4. How many liters of milk are there in the mixture?',
    options: ['20 liters', '15 liters', '10 liters', '5 liters'],
    correctAnswer: '20 liters',
    explanation: 'Let milk = 5x, water = 3x. After adding 4L: 5x:(3x+4) = 5:4, solving gives x = 4, so milk = 20L 🔍',
    difficulty: 'medium',
    marks: 2,
    recommendedTime: 55,
  },
  {
    id: 'cl8_ch7_t1_qm15',
    type: 'mcq',
    question: 'The ratio of boys to girls in a class is 5:4. If 6 more boys and 2 more girls join the class, the ratio becomes 3:2. How many students were initially in the class?',
    options: ['36', '45', '54', '63'],
    correctAnswer: '45',
    explanation: 'Let boys = 5x, girls = 4x. After joining: (5x+6)/(4x+2) = 3/2, solving gives x = 5, so total = 9x = 45 📊',
    difficulty: 'medium',
    marks: 2,
    recommendedTime: 60,
  },
  {
    id: 'cl8_ch7_t1_qm16',
    type: 'mcq',
    question: 'In what ratio must a 20% sugar solution be mixed with a 50% sugar solution to get a 30% sugar solution?',
    options: ['2:1', '1:2', '3:2', '2:3'],
    correctAnswer: '2:1',
    explanation: 'Using the rule of alligation: (50-30)/(30-20) = 20/10 = 2:1 🎯',
    difficulty: 'medium',
    marks: 2,
    recommendedTime: 50,
  },
  {
    id: 'cl8_ch7_t1_qm17',
    type: 'mcq',
    question: 'If a:b = 3:4 and b:c = 5:6, what is a:c?',
    options: ['5:8', '3:8', '15:24', '5:6'],
    correctAnswer: '15:24',
    explanation: 'a:b = 3:4, b:c = 5:6, so a:b:c = 3:4:4×(6/5) = 3:4:24/5 = 15:20:24, thus a:c = 15:24 🔢',
    difficulty: 'medium',
    marks: 2,
    recommendedTime: 55,
  },
  {
    id: 'cl8_ch7_t1_qm18',
    type: 'mcq',
    question: 'The price of a television was reduced by 20%. By what percent should the reduced price be increased to get back the original price?',
    options: ['20%', '25%', '30%', '35%'],
    correctAnswer: '25%',
    explanation: 'If original price is 100, new price is 80. To get back: 80 × (1+x/100) = 100, so x = 25% 📝',
    difficulty: 'medium',
    marks: 2,
    recommendedTime: 50,
  },
  {
    id: 'cl8_ch7_t1_qm19',
    type: 'mcq',
    question: 'A student scores 72 marks in a test and fails by 8 marks. If the minimum passing percentage is 40%, what is the maximum marks of the test?',
    options: ['175', '200', '225', '250'],
    correctAnswer: '200',
    explanation: 'Pass mark = 40% of maximum = 0.4x. Given: 72 + 8 = 0.4x, so 80 = 0.4x, thus x = 200 🧮',
    difficulty: 'medium',
    marks: 2,
    recommendedTime: 55,
  },
  {
    id: 'cl8_ch7_t1_qm20',
    type: 'mcq',
    question: 'A, B, and C share profits in the ratio 2:3:5. If C gets ₹400 more than A, what is the total profit?',
    options: ['₹1000', '₹1200', '₹1600', '₹2000'],
    correctAnswer: '₹2000',
    explanation: 'Let unit profit = x. Then C-A = 5x-2x = 3x = 400, so x = 400/3. Total = 10x = 10(400/3) = 4000/3 ≈ 1333.33 🔍',
    difficulty: 'medium',
    marks: 2,
    recommendedTime: 55,
  }
];
