import { QuizQuestion } from '../../../../../types';

export const easyQuestions: QuizQuestion[] = [
  {
    id: 'cl8_ch6_t2_qe1',
    type: 'mcq',
    question: 'What is the cube root of 64?',
    options: ['3', '4', '6', '8'],
    correctAnswer: '4',
    explanation: '4³ = 4 × 4 × 4 = 64, so ∛64 = 4 🧊',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t2_qe2',
    type: 'mcq',
    question: 'The cube root of 125 is:',
    options: ['4', '5', '25', '15'],
    correctAnswer: '5',
    explanation: '5³ = 5 × 5 × 5 = 125, so ∛125 = 5 📊',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t2_qe3',
    type: 'mcq',
    question: 'What is the cube root of 1?',
    options: ['0', '1', '3', '-1'],
    correctAnswer: '1',
    explanation: '1³ = 1 × 1 × 1 = 1, so ∛1 = 1 🔢',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t2_qe4',
    type: 'mcq',
    question: 'The cube root of 27 is:',
    options: ['3', '9', '2', '6'],
    correctAnswer: '3',
    explanation: '3³ = 3 × 3 × 3 = 27, so ∛27 = 3 🎯',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t2_qe5',
    type: 'mcq',
    question: 'What is the cube root of 1000?',
    options: ['10', '100', '1', '20'],
    correctAnswer: '10',
    explanation: '10³ = 10 × 10 × 10 = 1000, so ∛1000 = 10 🔍',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t2_qe6',
    type: 'mcq',
    question: 'The cube root of -8 is:',
    options: ['-2', '2', 'not defined', '-4'],
    correctAnswer: '-2',
    explanation: '(-2)³ = (-2) × (-2) × (-2) = -8, so ∛(-8) = -2 📝',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t2_qe7',
    type: 'mcq',
    question: 'What is the cube root of 8?',
    options: ['4', '2', '6', '3'],
    correctAnswer: '2',
    explanation: '2³ = 2 × 2 × 2 = 8, so ∛8 = 2 🧊',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t2_qe8',
    type: 'mcq',
    question: 'The digit in the unit place of a perfect cube can be:',
    options: ['0, 1, 4, 5, 6, and 9 only', '0, 1, 2, 3, 4, 5, 6, 7, 8, and 9', '0, 1, 2, 3 only', '1, 4, 5, 6, 9 only'],
    correctAnswer: '0, 1, 4, 5, 6, and 9 only',
    explanation: 'Perfect cubes only end in 0, 1, 4, 5, 6, or 9 🔢',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t2_qe9',
    type: 'mcq',
    question: 'Which of these is a perfect cube?',
    options: ['16', '27', '32', '50'],
    correctAnswer: '27',
    explanation: '27 = 3³ = 3 × 3 × 3, so it is a perfect cube 📊',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t2_qe10',
    type: 'mcq',
    question: 'The cube root of 0 is:',
    options: ['0', '1', '3', 'undefined'],
    correctAnswer: '0',
    explanation: '0³ = 0 × 0 × 0 = 0, so ∛0 = 0 🎯',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t2_qe11',
    type: 'mcq',
    question: 'What is the first step in finding the cube root by prime factorization?',
    options: ['Divide by 3', 'Find the prime factors', 'Group the factors in pairs', 'Cube the number'],
    correctAnswer: 'Find the prime factors',
    explanation: 'First find prime factors, then group in triplets to find cube root 🔍',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t2_qe12',
    type: 'mcq',
    question: 'The cube root of 216 is:',
    options: ['5', '6', '36', '72'],
    correctAnswer: '6',
    explanation: '6³ = 6 × 6 × 6 = 216, so ∛216 = 6 🧮',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t2_qe13',
    type: 'mcq',
    question: 'Which of these numbers is a perfect cube?',
    options: ['18', '64', '81', '100'],
    correctAnswer: '64',
    explanation: '64 = 4³ = 4 × 4 × 4, so it is a perfect cube 📏',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t2_qe14',
    type: 'mcq',
    question: 'If a number ends with 7, its cube will end with:',
    options: ['3', '7', '1', '9'],
    correctAnswer: '3',
    explanation: 'Cubes of numbers ending in 7 always end with 3 🔢',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t2_qe15',
    type: 'mcq',
    question: 'What is the cube root of 343?',
    options: ['5', '6', '7', '9'],
    correctAnswer: '7',
    explanation: '7³ = 7 × 7 × 7 = 343, so ∛343 = 7 🎯',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t2_qe16',
    type: 'mcq',
    question: 'If we have the prime factorization 2³ × 3³, the cube root is:',
    options: ['2 × 3', '6', '2³ × 3', '36'],
    correctAnswer: '2 × 3',
    explanation: 'The cube root of 2³ × 3³ = 2 × 3 = 6 🧮',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t2_qe17',
    type: 'mcq',
    question: 'The cube root of 512 is:',
    options: ['6', '8', '9', '4'],
    correctAnswer: '8',
    explanation: '8³ = 8 × 8 × 8 = 512, so ∛512 = 8 📊',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t2_qe18',
    type: 'mcq',
    question: 'How many prime factors would be in the prime factorization of a perfect cube?',
    options: ['At least 1', 'Any number', 'Multiple of 3', 'Always 3'],
    correctAnswer: 'Multiple of 3',
    explanation: 'Perfect cubes have prime factors in triplets (power divisible by 3) 🔍',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t2_qe19',
    type: 'mcq',
    question: 'The cube root of -27 is:',
    options: ['-3', '3', '9', 'not defined'],
    correctAnswer: '-3',
    explanation: '(-3)³ = (-3) × (-3) × (-3) = -27, so ∛(-27) = -3 🔢',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
  {
    id: 'cl8_ch6_t2_qe20',
    type: 'mcq',
    question: 'What is the cube root of 729?',
    options: ['7', '8', '9', '27'],
    correctAnswer: '9',
    explanation: '9³ = 9 × 9 × 9 = 729, so ∛729 = 9 🎯',
    difficulty: 'easy',
    marks: 1,
    recommendedTime: 30,
  },
];
